Feature/student chat
crowdbotics-apps/gaskap-23808 pull request #26
Opened 2021-01-14 21:39 UTC by misocho

### What does this PR do?

- Adds chat feature for students

2021-01-15 13:48 UTC, jlorencelim requested changes

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +        read_only = "id"
You can remove this since `id` is automatically `read_only`

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/consumers.py
> +        self.room_name_group = "chat_%s" % self.room_name
Use f-strings for string interpolation

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/consumers.py
> +        for message in messages:
Use list comprehension

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/consumers.py
> +            raise HttpResponseForbidden()
maybe raise a `ValidationError` adding the error message instead

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/models.py
> +        return self.contact.user.username
Better return the `content` for this.

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/models.py
> +    messages = models.ManyToManyField(
We can remove this field and add a chat foreign key to the Message model, since a message doesn't really appear in any other conversations so we don't need to make it a M2M

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/models.py
> +class Contact(TimeStampedModel):
We can remove this model, since it is very similar with how the `Profile` model works. No need to replicate.

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/utils.py
> +def get_current_chat(chat_id):
We don't to create a special function for this anymore. Yu can just use the `get_object_or_404` right away

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/admin.py
> +from django.contrib import admin
Please customize the admin (add list_display, search etc.) for easier testing and debugging

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +class ContactSerializer(serializers.StringRelatedField):
Better make this as a `ModelSerializer`

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +        chat = Chat()
You can just do a `Chat.objects.create()` here

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +        chat.save()
No need to do another `.save()` here

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/models.py
> +        return reverse("Contact_detail", kwargs={"pk": self.pk})
The get_absolute_url won't be used since we don't have a web component. No need to add code that won't be used

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/models.py
> +        return "{}".format(self.pk)
use f-strings for string interpolation

2021-01-15 13:48 UTC, jlorencelim commented on backend/chat/api/v1/viewsets.py
> +from rest_framework.authentication import SessionAuthentication, TokenAuthentication
Remove unused imports

2021-01-15 16:22 UTC, misocho commented on backend/chat/api/v1/viewsets.py
> +class ChatViewSet(viewsets.ViewSet):
The list method queries  the user's chats thus the need for coding my own list method. I'm not sure how I can achieve this without overriding the method.

2021-01-15 16:30 UTC, misocho commented on backend/chat/models.py
> +class Chat(models.Model):
I'll rename Chat to Thread I that will make it much more clearer.

2021-01-15 19:46 UTC, misocho commented on backend/chat/api/v1/serializers.py
> +        chat = Chat()
We need to first save a thread to the db in order to generate an id before adding the chat participants which has a many to many relationship with the user object. Without saving an initial chat instance we will get the following exception.

`"<Thread: None>" needs to have a value for field "id" before this many-to-many relationship can be used.
`

2021-01-15 20:07 UTC, misocho commented on backend/chat/api/v1/serializers.py
> +class ContactSerializer(serializers.StringRelatedField):
This was not intended as a model serializer but a [StringRelatedFeild](https://www.django-rest-framework.org/api-guide/relations/#stringrelatedfield) serializer. I need it to return the username instead of the user id for participants. I implemented it this way due to its `ReadOnly` limitation which won't work with post. It does introduce a technical debt, Please advice on a better solution for this.

2021-01-15 21:03 UTC, misocho commented on backend/chat/admin.py
> +from django.contrib import admin
Django admin does not support ManyToMany fields. Can you advise on how best to handle M2M fields on the admin.
![image](https://user-images.githubusercontent.com/29132159/104778315-34ef4280-578e-11eb-9f61-3739b11c9eff.png)

2021-01-16 04:23 UTC, jlorencelim requested changes

2021-01-16 04:23 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +        thread.save()
`thread.save()` is not needed here anymore. participants will be saved without calling this anymore

2021-01-16 04:23 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +    participants = ParticipantSerializer(many=True)
Rather than passing the username, I would suggest let it just pass in the `id` instead of the `username` since we aren't actually using that field for this app. It would just create confusion.
And since we will be using the default `id`, you won't need to override the `create` method anymore as by default, Django's model serializer handles this.

2021-01-16 04:23 UTC, jlorencelim commented on backend/chat/consumers.py
> +    def fetch_messages(self, data):
I would suggest rather than retrieving the last 10 messages in websocket, we would rather create an API endpoint for listing the messages of a specific thread with this, the endpoint will be more flexible and can access more than just the last 10 messages through pagination

2021-01-16 04:23 UTC, jlorencelim commented on backend/chat/consumers.py
> +        user_contact = get_object_or_404(User, username=self.me)
Your `self.me` is already a user instance. There's no need to query it again. Also, it's much more clearer to name this as `self.user` rather than `self.me`.

2021-01-16 04:23 UTC, jlorencelim commented on backend/chat/consumers.py
> +        self.room_name = self.scope["url_route"]["kwargs"]["room_name"]
Let's be consistent with the naming to prevent confusion. This `room_name` is actually the `thread_id` so better use the `thread_id` name instead

2021-01-16 04:23 UTC, jlorencelim commented on backend/chat/consumers.py
> +        if not self.isAuthorized():
Rather than checking if the user is authorized to send a message in this chat using this, it would be better to just do a proper query when retrieving the thread. So it would be something like this. 
```
thread = Thread.objects.filter(id=self.thread_id, participants=self.user).first()
if not thread:
    raise ValidationError
```

Let's take into account the number of queries you do since this affects performance and speed is a big factor for chat.

2021-01-16 04:23 UTC, jlorencelim commented on backend/chat/consumers.py
> +        current_chat = get_object_or_404(Thread, id=self.room_name)
Be consistent with the naming. We are not using the `chat` name anymore and we're using `thread`

2021-01-16 04:23 UTC, jlorencelim commented on backend/chat/models.py
> +        return f"{self.pk}"
You can actually just do a `return self.pk` here

2021-01-16 04:53 UTC, jlorencelim requested changes

2021-01-16 04:53 UTC, jlorencelim commented on backend/chat/consumers.py
> +        self.room_name_group = f"chat_{self.room_name}"
Same comments in the naming consistency.
Should be `thread_group` instead of `room_name_group`
and the string here should be `thread` instead of `chat`

2021-01-16 10:59 UTC, jlorencelim requested changes

2021-01-16 10:59 UTC, jlorencelim commented on backend/chat/admin.py
> +        return "\n".join([p.username for p in obj.participants.all()])
Let's not use the `username` since we aren't using this. Better use the `name` field.

2021-01-16 10:59 UTC, jlorencelim commented on backend/chat/api/v1/urls.py
> +router.register("message", viewsets.MessageViewSet, basename="message")
URLs should be in plural form. So `threads` instead of just `thread` and `messages` instead of just `message`

This should also be a nested router under thread so that it will be called as `api/v1/theads/<thread_id>/messages/`. You can checkout the `NestedSimpleRouter`

2021-01-16 10:59 UTC, jlorencelim commented on backend/chat/api/v1/viewsets.py
> +        user = get_object_or_404(User, username=username)
There's no need to query again the `user`. self.request.user is already a `user` instance. You can just do this for this method `return self.request.user.threads.all()`

2021-01-16 10:59 UTC, jlorencelim commented on backend/chat/api/v1/viewsets.py
> +        user = get_object_or_404(User, username=username)
Same here.

2021-01-16 10:59 UTC, jlorencelim commented on backend/chat/api/v1/viewsets.py
> +    permission_classes = [IsAuthenticated]
No need to define this. The default permission class for all endpoints is `IsAuthenticated`

2021-01-16 10:59 UTC, jlorencelim commented on backend/chat/api/v1/viewsets.py
> +    permission_classes = [IsAuthenticated]
No need to define this. The default permission class for all endpoints is `IsAuthenticated`

2021-01-16 10:59 UTC, jlorencelim commented on backend/chat/api/v1/viewsets.py
> +        serializer = self.get_serializer(self.get_queryset(), many=True)
This doesn't make sense. The request is a `GET` detail of a message but you are return a list. This should be shown in a `GET` list request and can be resolved with a nested router

2021-01-16 10:59 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +    def create(self, validated_data):
You can already remove overriding the create method. By default, this already handles the creation of thread and adding of participants since an `id` will now be passed.

2021-01-16 11:44 UTC, misocho commented on backend/chat/admin.py
> +        return "\n".join([p.username for p in obj.participants.all()])
I'll use the `id` since name can be null

2021-01-16 11:46 UTC, jlorencelim commented on backend/chat/admin.py
> +        return "\n".join([p.username for p in obj.participants.all()])
Better use the email then. But technically, `name` is required during registration.

2021-01-16 11:49 UTC, jlorencelim requested changes

2021-01-16 11:49 UTC, jlorencelim commented on backend/chat/api/v1/viewsets.py
> +            thread = Thread.objects.get(id=thread_id)
You can just do a `get_object_or_404` for this. This should still also filter to check if the current user is a participant of this thread

2021-01-16 11:49 UTC, jlorencelim commented on backend/chat/consumers.py
> +            "author": message.contact.username,
Better return the `id` since we are not using the `username`

2021-01-16 11:56 UTC, jlorencelim requested changes

2021-01-16 11:56 UTC, jlorencelim commented on backend/chat/api/v1/urls.py
> +router.register("threads", viewsets.ThreadViewSet, basename="thread")
also better, to set the basename as plural form for consistency. `threads`

2021-01-16 12:11 UTC, jlorencelim requested changes

2021-01-16 12:11 UTC, jlorencelim commented on backend/chat/admin.py
> +        return "\n".join([f"{p.id}" for p in obj.participants.all()])
no need to string interpolate here

2021-01-16 12:11 UTC, jlorencelim commented on backend/chat/admin.py
> +class ThreadAdmin(admin.ModelAdmin):
Please also also add the `search_display` for easier tracking of instances

2021-01-16 12:11 UTC, jlorencelim commented on backend/chat/admin.py
> +class MessageAdmin(admin.ModelAdmin):
Please also also add the `search_display` for easier tracking of instances

2021-01-16 12:14 UTC, misocho commented on backend/chat/admin.py
> +        return "\n".join([f"{p.id}" for p in obj.participants.all()])
Without the string interpolate an error is returned on the admin dashboard since it expects a string.

2021-01-16 12:15 UTC, jlorencelim commented on backend/chat/admin.py
> +        return "\n".join([f"{p.id}" for p in obj.participants.all()])
This is actually already returns a string since you are doing a `join`

2021-01-16 12:26 UTC, jlorencelim requested changes

2021-01-16 12:26 UTC, jlorencelim commented on backend/chat/api/v1/viewsets.py
> +    queryset = Message.objects.all()
Please add pagination on this.

2021-01-16 12:30 UTC, jlorencelim requested changes

2021-01-16 12:30 UTC, jlorencelim commented on backend/chat/admin.py
> +        return "\n".join([f"{p.id}" for p in obj.participants.all()])
But better just return the user's email for better visualization

2021-01-16 12:31 UTC, jlorencelim requested changes

2021-01-16 12:31 UTC, jlorencelim commented on backend/chat/admin.py
> +    search_display = ("id",)
better search for contact's name and content too

2021-01-16 13:01 UTC, jlorencelim approved these changes

2021-01-16 13:04 UTC, merged