Task/test chat
crowdbotics-apps/gaskap-23808 pull request #29
Opened 2021-01-20 17:57 UTC by misocho

2021-01-22 08:50 UTC, jlorencelim requested changes

2021-01-22 08:50 UTC, jlorencelim commented on backend/chat/models.py
> +        ordering = ["-id"]
Make sure to do `makemigrations` as changing the class `Meta` affects migrations

2021-01-22 08:50 UTC, jlorencelim commented on backend/chat/tests/test_models.py
> +import pytest
We have already started using Django unittests and not pytest. To keep it consistent, let's just use Django's unittest

2021-01-22 08:50 UTC, jlorencelim commented on backend/chat/tests/test_viewsets.py
> +    def test_list_tread_messages(self):
fix typo. should be `thread`

2021-01-22 08:50 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +    def validate_participants(self, participants):
Add unit tests for this validation

2021-01-22 08:50 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +        for participant in participants:
You can just do a single query for these conditions

2021-01-22 08:50 UTC, jlorencelim commented on backend/Pipfile
> +pytest-asyncio = "*"
We have already started using Django unittests and not pytest. To keep it consistent, let's just use Django's unittest

2021-01-22 18:25 UTC, misocho commented on backend/chat/api/v1/serializers.py
> +        for participant in participants:
Hi. I'm not sure how to achieve this. Could you please elaborate.

2021-01-25 03:16 UTC, jlorencelim requested changes

2021-01-25 03:16 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +        for participant in participants:
Something like this. 
```
if participants.filter(user_type__in=[User.USER_TYPE_STUDENT, User.USER_TYPE_PARENT]):
    raise PermissionDenied
```

2021-01-25 07:46 UTC, jlorencelim requested changes

2021-01-25 07:46 UTC, jlorencelim commented on backend/chat/api/v1/serializers.py
> +        participant_filter = filter(
If the solution can be done via 1 django query, then do it. Looping through a django query via python is a heavy transaction. Something like this
```
participants
    .filter(user_type__in=[User.USER_TYPE_STUDENT, User.USER_TYPE_PARENT])
    .exclude(id=participant.id)
```

2021-01-25 07:49 UTC, misocho commented on backend/chat/api/v1/serializers.py
> +        participant_filter = filter(
`participants` is not a django query. It's a list of user objects, the django query inbuilt functions won't work on it.

2021-01-25 07:54 UTC, jlorencelim approved these changes

2021-01-25 07:58 UTC, merged